### ISSUE TITLE
rama fails to build on nightly 1.98

### ISSUE THREAD

**Issue by GlenDC** [rust-lang/docs.rs#3393]
### Crate name

rama

### Build failure link

https://docs.rs/crate/rama/0.3.0-rc1/builds/3762820

### Additional details

This is since a couple of days, I have also for this reason moved rama's own CLI for our edge (main HEAD) docs to a more older version of nightly which does work (I now make it lag ~ 2 weeks behind tip edge rust).

**Comment by GuillaumeGomez** [comment]
Doesn't seem to have anything to do with docs.rs's rust version though?

**Comment by GlenDC** [comment]
With what does it have to do than? As it fails to build on docs.rs?
Guidance would be appreciated? Is this something I do wrong?

**Comment by GlenDC** [comment]
Ah I guess you mean that I need to file this issue in rustc / docgen, instead of here? Is that what you mean @GuillaumeGomez ?

**Comment by GuillaumeGomez** [comment]
The first error is:

```
cannot find function `worker_index` in module `tokio::runtime`
```

So it has nothing to do with docs.rs or rustc or rustdoc, the code is the issue.

**Comment by GlenDC** [comment]
Hmmm might be a `tokio_unstable` feature flag issue in that case that for some reason works in code but gives issues in doc generation.... It's a dependency though. Anyway will look into it. Sorry for the noise.

**Comment by GuillaumeGomez** [comment]
Don't forget to check if there is a `[package.metadata.docs.rs]` in a `Cargo.toml` as you can pass extra options with it.

**Comment by GlenDC** [comment]
I think I fixed it. If my theory is correct it is to do with our dial9 opt-in support as that stil requires unstable tokio. Have passed the appriate rustc `--cfg` flag now as well to enable it for docs.rs.

Thank you for the assist @GuillaumeGomez .

**Comment by GuillaumeGomez** [comment]
Glad to hear it!

**Comment by syphar** [comment]
@GlenDC if you want to make sure docs work in your CI, see also [the section about testing builds in CI](https://docs.rs/about/builds#testing-builds-ci). `cargo docs-rs` catches many of the potential issues that might happen in our builds.
